POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "User id of the note creator is at the start sent along the request",
  "important": true,
  "userId": "649419ce4b73b008551b5e0b"
}