GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lIG1heSBiZW8gZ2FnYWdhIiwiaWQiOiI2NDk1MTNhNjYzZDJmOWQyYjFhOWY2MmUiLCJpYXQiOjE2ODc4MzgxODUsImV4cCI6MTY4Nzg0MTc4NX0.97DR6wITOqDJ_7Q6yK_QwjR6HO__WKPsVreNw2OxBKc