GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lIG1heSBiZW8gZ2FnYWdhIiwiaWQiOiI2NDk1MTNhNjYzZDJmOWQyYjFhOWY2MmUiLCJpYXQiOjE2ODc1MDg1ODMsImV4cCI6MTY4NzUxMjE4M30.eJtFaVqx7aj4h0-gt1yeRQZN2cYBIIYn4SAOtN8cDzM